spring.application.name=PixelReveal-Back
app.upload.dir=uploads

spring.config.import=optional:file:./.example.env[.properties],file:./.env[.properties]
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB